set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN D23 [get_ports clk]
set_property PACKAGE_PIN A18 [get_ports bt3]
set_property IOSTANDARD LVCMOS33 [get_ports bt3]
set_property PACKAGE_PIN E11 [get_ports sw0]
set_property IOSTANDARD LVCMOS33 [get_ports sw0]
set_property PACKAGE_PIN J23 [get_ports codec_lrclk]
set_property IOSTANDARD LVCMOS33 [get_ports codec_lrclk]
set_property PACKAGE_PIN K22 [get_ports vol_clk]
set_property IOSTANDARD LVCMOS33 [get_ports vol_clk]
set_property PACKAGE_PIN H22 [get_ports vol_ud]
set_property IOSTANDARD LVCMOS33 [get_ports vol_ud]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_pll_out]
