# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k70tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.cache/wt [current_project]
set_property parent.project_path C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/new/DDS_top.v
  C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/new/I2S_codec.v
  C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/new/RND_GEN.v
  C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/new/SIN_LUT.v
  C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/new/DDS_tl.v
}
read_ip -quiet C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/vio_DDS/vio_DDS.xci
set_property used_in_implementation false [get_files -all c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/vio_DDS/vio_DDS.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/vio_DDS/vio_DDS_ooc.xdc]
set_property is_locked true [get_files C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/vio_DDS/vio_DDS.xci]

read_ip -quiet c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files c:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/constrs_2/new/pinout.xdc
set_property used_in_implementation false [get_files C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/logterv/DDS/DDS.srcs/constrs_2/new/pinout.xdc]


synth_design -top DDS_tl -part xc7k70tfbg676-1


write_checkpoint -force -noxdef DDS_tl.dcp

catch { report_utilization -file DDS_tl_utilization_synth.rpt -pb DDS_tl_utilization_synth.pb }
