webtalk_init -webtalk_dir C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/rendszer/spi_master/spi_master.sim/sim_1/behav/xsim.dir/AXI_MASTER_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 28 22:12:40 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1909853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "50626ffdcdb8524ab4a35b39496f311a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6ce234fb5f8740cf9cf73690e780cc41" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "625 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2637819291 -regid "" -xml C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/rendszer/spi_master/spi_master.sim/sim_1/behav/xsim.dir/AXI_MASTER_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/rendszer/spi_master/spi_master.sim/sim_1/behav/xsim.dir/AXI_MASTER_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Peti/Documents/VIK_MSc/rendszer/rendszer_hf/rendszer/spi_master/spi_master.sim/sim_1/behav/xsim.dir/AXI_MASTER_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
